name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Security Scan (HTML Check)
        run: |
          echo "Running basic security check..."
          if grep -r "<script>" .; then
            echo "Warning: Script tag found!"
          else
            echo "No risky scripts found."
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .